CREATE DATABASE Property_DB;

CREATE TABLE IF NOT EXISTS lease(
  leaseID INT NOT NULL AUTO_INCREMENT,
  startDate DATE NOT NULL,
  endDate DATE,
  rentDueDate DATE NOT NULL,
  rentAmount DECIMAL(13,2) NOT NULL,
  isActive BOOLEAN NOT NULL,
  PRIMARY KEY(leaseID)
);

CREATE TABLE IF NOT EXISTS renter(
  renterID INT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(256) NOT NULL,
  lastName VARCHAR(256) NOT NULL,
  email VARCHAR(256),
  phoneNumber VARCHAR(13),
  PRIMARY KEY(renterID)
);

CREATE TABLE IF NOT EXISTS property(
  propertyID INT NOT NULL AUTO_INCREMENT,
  propertyName VARCHAR(256) NOT NULL,
  streetAddress VARCHAR(256) NOT NULL,
  city VARCHAR(256),
  zip VARCHAR(10),
  unitNumber INT NOT NULL,
  PRIMARY KEY(propertyID)
);

CREATE TABLE IF NOT EXISTS renterLease(
  renterID INT NOT NULL,
  leaseID INT NOT NULL,
  FOREIGN KEY renterID_fk (renterID) REFERENCES renter (renterID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY leaseID_fk (leaseID) REFERENCES lease (leaseID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS propertyLease(
  propertyID INT NOT NULL,
  leaseID INT NOT NULL,
  FOREIGN KEY propertyID_fk (propertyID) REFERENCES property (propertyID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY leaseID_fk_property (leaseID) REFERENCES lease (leaseID) ON DELETE RESTRICT ON UPDATE CASCADE
);


DELIMITER $$
CREATE TRIGGER activeLease
    BEFORE UPDATE ON lease
    FOR EACH ROW
BEGIN

    IF (NEW.endDate IS NULL) THEN
      SET NEW.isActive = FALSE;
    ELSE
      SET NEW.isActive = TRUE;
    END IF;
END$$
DELIMITER ;
